name: Kaggle Badges and GitHub Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "11 11 1 * *" # 1st of every month at 11:11 AM
    - cron: "0 0 * * *"   # Every 24 hours
  workflow_dispatch:

jobs:
  create-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome@126.0.6478.63

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v1.2.2
        with:
          user_name: { Your Kaggle Username }

      - name: Commit and Push SVG files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/* ./kaggle-plates/*
          git commit -m "Add generated SVG files" || echo "No changes to commit"
          git push

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.base.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: output/details.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          repositories_skipped: chatbot-ui, gitHub-readme-stats-clone, PL0-compiler
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, qmake, lex, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
